### ISSUE TITLE
Enemy Checklist

### ISSUE THREAD

**Issue by TristanCopley** [TristanCopley/project-z#8]
Properties and functions of enemies:

- [x] Get enemies drawing to the screen
- [x] Enemies have different properties
- [x] Enemies can run towards a point (Without pathfinding around objects) (This is useful for tracking the player as well as swapping to a decoy or something)
- [x] Enemies have collision with themselves
- [ ] Enemies have collision with the player
- [ ] Enemy animations and assets

Future:

- [ ] Update AI to run around objects
